version: 2.1
jobs:
  api-build:
    docker:
      - image: circleci/node:current-buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build API image
          working_directory: ~/project/docker
          command: docker-compose -f docker-compose.yml -f prod.yml build api
workflows:
    build-and-test:
      jobs:
        - api-build
