version: 2.1
jobs:
  api-build:
    docker:
      - image: circleci/node:current-buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build API image
          working_directory: ~/project/docker
          command: docker-compose -f docker-compose.yml -f prod.yml build api
      - run:
          name: Push API image
          command: |
            docker login -u="scjody+den_ci" -p=$QUAY_TOKEN quay.io
            docker tag den-api quay.io/scjody/den-api:b$CIRCLE_BUILD_NUM
            docker push quay.io/scjody/den-api:b$CIRCLE_BUILD_NUM

  api-test:
    docker:
      - image: circleci/node:current-buster
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: Add hosts entry for DB
          command: echo 127.0.0.1 db | sudo tee -a /etc/hosts
      - run:
          name: yarn install for API
          working_directory: ~/project/api
          command: yarn install
      - run:
          name: Copy and build activitypub
          command: |
            cp -a activitypub api/node_modules
            cd api/node_modules/activitypub
            yarn install
            yarn build
      - run:
          name: Build (includes linting and flow check)
          working_directory: ~/project/api
          command: yarn build
      - run:
          name: Run tests
          working_directory: ~/project/api
          command: yarn test

workflows:
    build-and-test:
      jobs:
        - api-build
        - api-test
