version: '3'

volumes:
  data-volume:

services:

  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile.dev
    image: den-server
    ports:
      - 80:80
    depends_on:
      - api
      - app

  app:
    build:
      context: ../.
      dockerfile: docker/app/Dockerfile.dev
    image: den-app
    environment:
      - NODE_ENV=development
    volumes:
      - ./../app:/usr/src/app
    ports:
      - 3000:3000 # For docker to now where to redirect HMR queries

  api:
    build:
      context: ../.
      dockerfile: docker/api/Dockerfile.dev
    image: den-api
    environment:
      - NODE_ENV=development
    links:
      - db:db
    volumes:
      - ./../api:/usr/src/api
    ports:
      - 8080
    depends_on:
      - db

  db:
    container_name: den-db
    image: mongo:latest
    volumes:
      - data-volume:/data/db