version: '3.4'

volumes:
  data-volume:

services:

  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile.dev
    image: den-server
    ports:
      - 80:80
    depends_on:
      - api
      - app

  app:
    build: 
      context: ../app
      dockerfile: Dockerfile.dev
    image: den-app

  api:
    build:
      context: ..
      dockerfile: api/Dockerfile.dev
    image: den-api
    links:
      - db:db
    depends_on:
      - db

  db:
    container_name: den-db
    image: mongo:latest
    volumes:
      - data-volume:/data/db
