version: '3'

volumes:
  data-volume:

services:

  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile.dev
    image: den-server
    ports:
      - 80:80
    depends_on:
      - api
      - app

  app:
    build: 
      context: ../app
      dockerfile: Dockerfile.dev
    image: den-app
    environment:
      - NODE_ENV=development
    volumes:
      - ../app:/opt/app
    ports:
      - 3000:3000 # For docker to now where to redirect HMR queries

  api:
    build:
      context: ../api
      dockerfile: Dockerfile.dev
    image: den-api
    environment:
      - NODE_ENV=development
    links:
      - db:db
    volumes:
      - ../api:/opt/api
      - /opt/api/node_modules # anonymous volume for node_modules only
    ports:
      - 8080:8080 # unbind this in prod
      - 9229:9229 # node debugger
    depends_on:
      - db

  db:
    container_name: den-db
    image: mongo:latest
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017 # unbind this in prod