FROM node:latest

# use changes to package.json to force Docker not to use the cache
# when we change our application's nodejs dependencies:
ADD package.json /tmp/package.json
ADD yarn.lock /tmp/yarn.lock
RUN cd /tmp && yarn install && yarn add --force bcrypt
RUN mkdir -p /opt/api && cp -a /tmp/node_modules /opt/api/

WORKDIR /opt/api

EXPOSE 8080
EXPOSE 9229

CMD [ "yarn", "start" ]